/**
 * Seed scenario library. In a later phase these move to Firestore so they can be
 * edited without a deploy, but hardcoding the MVP set keeps the app usable offline
 * and with zero setup. Each scenario drives the tutor's system prompt.
 *
 * levels: A0 (absolute beginner) → C1 (advanced), roughly CEFR-aligned.
 */
const SCENARIOS = [
  {
    id: 'ordering-food',
    title: 'Ordering Food',
    emoji: '🍔',
    theme: 'daily',
    level: 'A1',
    description: 'Order a meal at a restaurant and talk to the waiter.',
    setup: 'You are a friendly waiter at a casual restaurant. The learner is a customer who just sat down.',
    goals: ['Greet and be seated', 'Order a drink and a main dish', 'Ask for the bill'],
    starter: 'Hi there! Welcome. Here is the menu — can I get you something to drink first?',
    keywords: ['menu', 'order', 'drink', 'main course', 'bill', 'delicious', 'recommend'],
  },
  {
    id: 'job-interview',
    title: 'Job Interview',
    emoji: '💼',
    theme: 'work',
    level: 'B1',
    description: 'Practice a simple job interview for an entry-level role.',
    setup: 'You are a polite hiring manager interviewing the learner for an entry-level job. Ask common interview questions one at a time.',
    goals: ['Introduce yourself', 'Talk about your strengths', 'Ask a question about the role'],
    starter: "Thanks for coming in today. To start, could you tell me a little about yourself?",
    keywords: ['experience', 'strength', 'weakness', 'team', 'responsibility', 'salary', 'opportunity'],
  },
  {
    id: 'shopping',
    title: 'Shopping for Clothes',
    emoji: '🛍️',
    theme: 'daily',
    level: 'A1',
    description: 'Buy clothes: ask for size, color, and price.',
    setup: 'You are a helpful shop assistant in a clothing store. The learner wants to buy something.',
    goals: ['Ask for a size', 'Ask the price', 'Decide to buy or not'],
    starter: 'Hello! Are you looking for anything in particular today?',
    keywords: ['size', 'price', 'try on', 'fit', 'color', 'discount', 'receipt'],
  },
  {
    id: 'doctor-visit',
    title: 'At the Doctor',
    emoji: '🏥',
    theme: 'daily',
    level: 'A2',
    description: 'Describe symptoms to a doctor.',
    setup: 'You are a kind doctor. The learner is a patient describing how they feel. Ask gentle follow-up questions.',
    goals: ['Describe a symptom', 'Answer the doctor’s questions', 'Understand the advice'],
    starter: 'Good morning. Please have a seat. So, what seems to be the problem today?',
    keywords: ['pain', 'fever', 'headache', 'medicine', 'rest', 'prescription', 'appointment'],
  },
  {
    id: 'small-talk',
    title: 'Making Small Talk',
    emoji: '💬',
    theme: 'social',
    level: 'A2',
    description: 'Chat casually with a new acquaintance.',
    setup: 'You are a friendly person meeting the learner at a social event. Keep the conversation light and ask about their hobbies, work, and weekend.',
    goals: ['Introduce yourself', 'Ask and answer casual questions', 'Keep the conversation going'],
    starter: "Hi! I don't think we've met — I'm Alex. So, what do you do?",
    keywords: ['hobby', 'weekend', 'weather', 'interesting', 'nice to meet you', 'by the way'],
  },
  {
    id: 'airport',
    title: 'At the Airport',
    emoji: '✈️',
    theme: 'travel',
    level: 'A2',
    description: 'Check in for a flight and pass through the gate.',
    setup: 'You are an airline check-in agent. The learner is a traveler checking in for a flight.',
    goals: ['Check in and show your passport', 'Ask about your gate and baggage', 'Understand boarding info'],
    starter: 'Good afternoon! May I see your passport and ticket, please?',
    keywords: ['passport', 'boarding pass', 'gate', 'luggage', 'window seat', 'delay', 'departure'],
  },
  {
    id: 'coffee-shop',
    title: 'At a Coffee Shop',
    emoji: '☕',
    theme: 'daily',
    level: 'A1',
    description: 'Order a coffee and a snack to go.',
    setup: 'You are a friendly barista at a coffee shop. The learner is a customer ordering a drink.',
    goals: ['Order a drink', 'Choose size and milk', 'Pay and say thanks'],
    starter: 'Hi! Welcome in. What can I get started for you today?',
    keywords: ['coffee', 'size', 'milk', 'sugar', 'to go', 'card', 'change'],
  },
  {
    id: 'directions',
    title: 'Asking for Directions',
    emoji: '🗺️',
    theme: 'travel',
    level: 'A1',
    description: 'Ask a stranger how to get to a place.',
    setup: 'You are a friendly local on the street. The learner is lost and asks you for directions. Give simple, clear directions.',
    goals: ['Ask where a place is', 'Understand left/right/straight', 'Say thank you'],
    starter: 'Hi, you look a little lost — do you need some help?',
    keywords: ['left', 'right', 'straight', 'corner', 'near', 'far', 'crossing'],
  },
  {
    id: 'phone-call',
    title: 'A Work Phone Call',
    emoji: '📞',
    theme: 'work',
    level: 'A2',
    description: 'Take a simple phone call and pass a message.',
    setup: 'You are a caller phoning the learner’s office. Ask to speak to someone and leave a message. Speak clearly and naturally.',
    goals: ['Answer the phone politely', 'Take a message', 'Confirm details'],
    starter: 'Hello, good morning. Am I speaking with the reception? I’d like to reach Mr. Sharma.',
    keywords: ['speaking', 'message', 'call back', 'available', 'hold on', 'reach', 'confirm'],
  },
  {
    id: 'hotel-checkin',
    title: 'Hotel Check-in',
    emoji: '🏨',
    theme: 'travel',
    level: 'A2',
    description: 'Check into a hotel and ask about facilities.',
    setup: 'You are a hotel receptionist. The learner is a guest checking in. Be warm and helpful.',
    goals: ['Give your booking name', 'Ask about breakfast and wifi', 'Get your room key'],
    starter: 'Good evening and welcome! Do you have a reservation with us?',
    keywords: ['reservation', 'room', 'breakfast', 'wifi', 'key', 'checkout', 'floor'],
  },
  {
    id: 'renting-apartment',
    title: 'Renting an Apartment',
    emoji: '🏠',
    theme: 'survival',
    level: 'B1',
    description: 'Talk to a landlord about renting a place.',
    setup: 'You are a landlord showing an apartment. The learner is a possible tenant asking questions. Answer naturally.',
    goals: ['Ask about rent and rooms', 'Ask what is included', 'Discuss moving in'],
    starter: 'Hello! Thanks for coming to see the apartment. Shall I show you around?',
    keywords: ['rent', 'deposit', 'furnished', 'utilities', 'lease', 'landlord', 'tenant'],
  },
  {
    id: 'gym',
    title: 'Joining a Gym',
    emoji: '🏋️',
    theme: 'social',
    level: 'A2',
    description: 'Ask about gym plans and timings.',
    setup: 'You are a gym receptionist. The learner wants to join. Explain plans and timings simply.',
    goals: ['Ask about membership', 'Ask about timings and classes', 'Decide on a plan'],
    starter: 'Hey there! Looking to join us? I can walk you through our plans.',
    keywords: ['membership', 'monthly', 'trainer', 'class', 'timing', 'equipment', 'trial'],
  },
  {
    id: 'online-meeting',
    title: 'Online Team Meeting',
    emoji: '💻',
    theme: 'work',
    level: 'B1',
    description: 'Join a video call and share a quick update.',
    setup: 'You are a team lead running a short online stand-up meeting. Ask the learner for their update and react naturally.',
    goals: ['Greet the team', 'Give a short update', 'Ask or answer a question'],
    starter: 'Morning everyone! Let’s do a quick round — could you share what you worked on yesterday?',
    keywords: ['update', 'progress', 'blocker', 'deadline', 'agenda', 'follow up', 'mute'],
  },
  {
    id: 'gaming-voice',
    title: 'Gaming with Friends',
    emoji: '🎮',
    theme: 'social',
    level: 'B1',
    description: 'Team up on a voice chat during a game.',
    setup: 'You are a friendly teammate in an online game voice chat. Talk casually and use common gaming phrases.',
    goals: ['Coordinate with your team', 'React to the game', 'Use casual gaming slang'],
    starter: 'Yo! Glad you joined. Okay, they’re pushing mid — what’s the plan?',
    keywords: ['team', 'push', 'cover me', 'nice one', 'respawn', 'strategy', 'gg'],
  },
  {
    id: 'pharmacy',
    title: 'At the Pharmacy',
    emoji: '💊',
    theme: 'daily',
    level: 'A2',
    description: 'Buy medicine and understand the instructions.',
    setup: 'You are a pharmacist. The learner needs medicine for a common problem. Explain how to take it simply.',
    goals: ['Explain your problem', 'Ask how to take the medicine', 'Ask about the price'],
    starter: 'Hello, how can I help you today?',
    keywords: ['medicine', 'tablet', 'twice a day', 'after food', 'dose', 'prescription', 'side effect'],
  },
  {
    id: 'restaurant-reservation',
    title: 'Booking a Table',
    emoji: '🍽️',
    theme: 'social',
    level: 'A2',
    description: 'Call a restaurant to reserve a table.',
    setup: 'You are a restaurant host taking a reservation over the phone. Confirm the details clearly.',
    goals: ['Ask for a table', 'Give date, time, and number of people', 'Confirm the booking'],
    starter: 'Thank you for calling The Garden Restaurant. How can I help you?',
    keywords: ['reservation', 'table', 'tonight', 'people', 'name', 'confirm', 'available'],
  },
];

function listScenarios() {
  return SCENARIOS.map(({ setup, ...pub }) => pub); // hide the internal system-prompt setup
}

function getScenario(id) {
  return SCENARIOS.find((s) => s.id === id) || null;
}

module.exports = { listScenarios, getScenario, SCENARIOS };
